include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - build/**

linter:
  rules:
    # Basic quality rules
    avoid_print: false  # Allow print statements for now
    prefer_const_constructors: false  # Disable to reduce warnings
    prefer_const_literals_to_create_immutables: false
    require_trailing_commas: false
    avoid_redundant_argument_values: false
    use_super_parameters: false
