name: exam_coach_app
description: A comprehensive exam preparation application with AI-powered coaching and real-time progress tracking.
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.8
  
  # Logging
  logger: ^2.4.0
  
  # HTTP Requests
  http: ^1.2.2
  
  # Environment Configuration
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Assets (secure asset handling)
  # assets:
  #   - assets/images/
  #   - assets/icons/
