name: exam_coach_app
description: A secure Flutter app for exam coaching with personalized quizzes.
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  logger: ^2.0.0
  flutter_secure_storage: ^9.0.0
  
  # HTTP requests for additional API calls if needed
  http: ^1.1.0
  
  # Connectivity checking
  connectivity_plus: ^5.0.0
  
  # Firebase for production authentication
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Assets (secure asset handling)
  # assets:
  #   - assets/images/
  #   - assets/icons/ 