// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform, kDebugMode;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// SECURITY NOTE: Firebase Web API keys are PUBLIC by design and should NOT be hidden.
/// Real security comes from:
/// 1. Firebase Security Rules (primary security layer)
/// 2. Domain restrictions in Firebase Console
/// 3. API key restrictions in Google Cloud Console
///
/// PRODUCTION FIREBASE PROJECT: examcoachapp
/// - Project ID: examcoachapp
/// - Auth Domain: examcoachapp.firebaseapp.com
/// - Real SMS/OTP will be sent when running in production mode
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web Firebase configuration for examcoachapp project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZrX5BY7fMPWFC7rxMZUxKLiFBzi7tP9I',
    appId: '1:591013189256:web:bb2dc0867996839a40f13d',
    messagingSenderId: '591013189256',
    projectId: 'examcoachapp',
    authDomain: 'examcoachapp.firebaseapp.com',
    storageBucket: 'examcoachapp.firebasestorage.app',
    measurementId: 'G-RP4T27J6KB',
  );

  /// Android Firebase configuration (add when needed)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY_HERE',
    appId: 'YOUR_ANDROID_APP_ID_HERE',
    messagingSenderId: '591013189256',
    projectId: 'examcoachapp',
    storageBucket: 'examcoachapp.firebasestorage.app',
  );

  /// iOS Firebase configuration (add when needed)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY_HERE',
    appId: 'YOUR_IOS_APP_ID_HERE',
    messagingSenderId: '591013189256',
    projectId: 'examcoachapp',
    storageBucket: 'examcoachapp.firebasestorage.app',
    iosBundleId: 'com.example.examcoachapp',
  );

  /// macOS Firebase configuration (add when needed)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY_HERE',
    appId: 'YOUR_MACOS_APP_ID_HERE',
    messagingSenderId: '591013189256',
    projectId: 'examcoachapp',
    storageBucket: 'examcoachapp.firebasestorage.app',
    iosBundleId: 'com.example.examcoachapp',
  );
} 