// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Replace the placeholder values below with your actual Firebase project configuration.
/// To get these values:
/// 1. Go to https://console.firebase.google.com
/// 2. Select your project
/// 3. Click the gear icon (settings) → Project settings
/// 4. Scroll to 'Your apps' section
/// 5. Add a web app if not already added
/// 6. Copy the config object (const firebaseConfig = { ... })
/// 7. Paste the values here for 'web'
/// 8. For Android/iOS: Add apps and copy their configs too
///
/// After updating, commit and push to enable real SMS in deployed app!
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key-here',  // From firebaseConfig.apiKey
    appId: 'your-web-app-id-here',    // From firebaseConfig.appId
    messagingSenderId: 'your-sender-id-here',  // From firebaseConfig.messagingSenderId
    projectId: 'your-project-id-here',  // From firebaseConfig.projectId
    authDomain: 'your-project-id.firebaseapp.com',  // From firebaseConfig.authDomain
    storageBucket: 'your-project-id.appspot.com',  // From firebaseConfig.storageBucket
    measurementId: 'your-measurement-id-here',  // From firebaseConfig.measurementId
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key-here',
    appId: 'your-android-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'your-project-id-here',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key-here',
    appId: 'your-ios-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'your-project-id-here',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.examCoachApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-ios-api-key-here',
    appId: 'your-ios-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'your-project-id-here',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.examCoachApp',
  );
} 